### ISSUE TITLE
Some of the announcements do not dissapear 

### ISSUE THREAD

**Issue by Swordancer** [Sama34/OUGC-Announcement-Bars#15]
Some of the announcements do not dissapear when they expire, even when i remove them. It's mybb 1.8.5 problem. I rebuilded caches, reinstalled plugin many times, but nothing.

**Comment by Sama34** [comment]
Did it worked before? Are you using the Mods site package or the repository files?

**Comment by Swordancer** [comment]
Im using files from mybb.com, and it never worked (latest version). I guess that plugin do not removing table with announcement from mysql base (datacache table), but im not sure if this is the reason of this problem.

**Comment by Sama34** [comment]
There is a known issue where deleting the last bar does not refreshes the cache, this may be the same case.

To temporally "fix" just create a new bar that no one will be able to see, or that it doesn't matter if they do, like a "You are banned!" bar visible only to a banned group.

**Comment by Sama34** [comment]
#6

Apply the following fix otherwise:
https://github.com/Sama34/OUGC-Announcement-Bars/commit/eb45a424b1f3f008d8549ffd6369462f40ef9c36#diff-ec48180cfa8711c4c8950f2fbd3a5cf5R222 (line #223)
