### ISSUE TITLE
sql error with latest version

### ISSUE THREAD

**Issue by guven5** [Sama34/OUGC-Announcement-Bars#17]
just fixed mybb plugin page slow issue and tried to update Announcement plugin to latest but nothing work, all files upload done but when i try to activate plugin mybb page gives error

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
    1054 - Unknown column 'startdate' in 'where clause'
Query:
    SELECT * FROM mybb_ougc_annbars WHERE startdate>'1486906242' 

what is wrong or missing, really old version was working and i feel disappointment

**Comment by Sama34** [comment]
You need to deactivate the plugin before uploading new files.
