### ISSUE TITLE
Start date validation error

### ISSUE THREAD

**Issue by wingedcatgirl** [Sama34/OUGC-Announcement-Bars#23]
When creating or updating an announcement bar, the script will check to make sure the start date is earlier than the end date, and throw an error preventing the bar from being saved if it is not. However, the script will erroneously fail if the start day is an earlier day in a later month of the same year (e.g. May 28, 2021 is erroneously blocked as an invalid start date when the end date is June 18, 2021, but not when it is June 29, 2021 or any date in 2022)

Conversely, it will erroneously _not_ fail when the start date is a later day in an earlier month of the same year.

**Comment by Sama34** [comment]
Hi, please download from the develop branch, simply replace your old files.
https://github.com/Sama34/OUGC-Announcement-Bars/commit/4cbd8be4e523aa5283401e5b55b9f7b79b8e0bf1

**Comment by Sama34** [comment]
https://github.com/Sama34/OUGC-Announcement-Bars/pull/25/commits/4cbd8be4e523aa5283401e5b55b9f7b79b8e0bf1
